repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
    - id: pyright