name: Publish on PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1

